<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

Country::truncate();
        $countries = [
            ['en' => 'Egypt', 'ar' => 'مصر'],
            ['en' => 'Saudi Arabia', 'ar' => 'المملكة العربية السعودية'],
            ['en' => 'United Arab Emirates', 'ar' => 'الإمارات العربية المتحدة'],
        ];
        // $countries = [
        //     ['en' => 'Afghanistan', 'ar' => 'أفغانستان'],
        //     ['en' => 'Åland Islands', 'ar' => 'جزر آلاند'],
        //     ['en' => 'Albania', 'ar' => 'ألبانيا'],
        //     ['en' => 'Algeria', 'ar' => 'الجزائر'],
        //     ['en' => 'American Samoa', 'ar' => 'ساموا الأمريكية'],
        //     ['en' => 'Andorra', 'ar' => 'أندورا'],
        //     ['en' => 'Angola', 'ar' => 'أنغولا'],
        //     ['en' => 'Anguilla', 'ar' => 'أنغيلا'],
        //     ['en' => 'Antarctica', 'ar' => 'أنتاركتيكا'],
        //     ['en' => 'Antigua and Barbuda', 'ar' => 'أنتيغوا وبربودا'],
        //     ['en' => 'Argentina', 'ar' => 'الأرجنتين'],
        //     ['en' => 'Armenia', 'ar' => 'أرمينيا'],
        //     ['en' => 'Aruba', 'ar' => 'أروبا'],
        //     ['en' => 'Australia', 'ar' => 'أستراليا'],
        //     ['en' => 'Austria', 'ar' => 'النمسا'],
        //     ['en' => 'Azerbaijan', 'ar' => 'أذربيجان'],
        //     ['en' => 'Bahamas', 'ar' => 'الباهاما'],
        //     ['en' => 'Bahrain', 'ar' => 'البحرين'],
        //     ['en' => 'Bangladesh', 'ar' => 'بنغلاديش'],
        //     ['en' => 'Barbados', 'ar' => 'بربادوس'],
        //     ['en' => 'Belarus', 'ar' => 'بيلاروسيا'],
        //     ['en' => 'Belgium', 'ar' => 'بلجيكا'],
        //     ['en' => 'Belize', 'ar' => 'بليز'],
        //     ['en' => 'Benin', 'ar' => 'بنين'],
        //     ['en' => 'Bermuda', 'ar' => 'برمودا'],
        //     ['en' => 'Bhutan', 'ar' => 'بوتان'],
        //     ['en' => 'Bolivia, Plurinational State of', 'ar' => 'بوليفيا'],
        //     ['en' => 'Bonaire, Sint Eustatius and Saba', 'ar' => 'بونير وسانت أوستاتيوس وسابا'],
        //     ['en' => 'Bosnia and Herzegovina', 'ar' => 'البوسنة والهرسك'],
        //     ['en' => 'Botswana', 'ar' => 'بوتسوانا'],
        //     ['en' => 'Bouvet Island', 'ar' => 'جزيرة بوفيه'],
        //     ['en' => 'Brazil', 'ar' => 'البرازيل'],
        //     ['en' => 'British Indian Ocean Territory', 'ar' => 'إقليم المحيط الهندي البريطاني'],
        //     ['en' => 'Brunei Darussalam', 'ar' => 'بروناي'],
        //     ['en' => 'Bulgaria', 'ar' => 'بلغاريا'],
        //     ['en' => 'Burkina Faso', 'ar' => 'بوركينا فاسو'],
        //     ['en' => 'Burundi', 'ar' => 'بوروندي'],
        //     ['en' => 'Cambodia', 'ar' => 'كمبوديا'],
        //     ['en' => 'Cameroon', 'ar' => 'الكاميرون'],
        //     ['en' => 'Canada', 'ar' => 'كندا'],
        //     ['en' => 'Cape Verde', 'ar' => 'الرأس الأخضر'],
        //     ['en' => 'Cayman Islands', 'ar' => 'جزر كايمان'],
        //     ['en' => 'Central African Republic', 'ar' => 'جمهورية أفريقيا الوسطى'],
        //     ['en' => 'Chad', 'ar' => 'تشاد'],
        //     ['en' => 'Chile', 'ar' => 'تشيلي'],
        //     ['en' => 'China', 'ar' => 'الصين'],
        //     ['en' => 'Christmas Island', 'ar' => 'جزيرة الكريسماس'],
        //     ['en' => 'Cocos (Keeling) Islands', 'ar' => 'جزر كوكوس'],
        //     ['en' => 'Colombia', 'ar' => 'كولومبيا'],
        //     ['en' => 'Comoros', 'ar' => 'جزر القمر'],
        //     ['en' => 'Congo', 'ar' => 'الكونغو'],

        //     ['en' => 'Cook Islands', 'ar' => 'جزر كوك'],
        //     ['en' => 'Costa Rica', 'ar' => 'كوستاريكا'],
        //     ['en' => 'Côte d\'Ivoire', 'ar' => 'ساحل العاج'],
        //     ['en' => 'Croatia', 'ar' => 'كرواتيا'],
        //     ['en' => 'Cuba', 'ar' => 'كوبا'],
        //     ['en' => 'Curaçao', 'ar' => 'كوراساو'],
        //     ['en' => 'Cyprus', 'ar' => 'قبرص'],
        //     ['en' => 'Czech Republic', 'ar' => 'جمهورية التشيك'],
        //     ['en' => 'Denmark', 'ar' => 'الدنمارك'],
        //     ['en' => 'Djibouti', 'ar' => 'جيبوتي'],
        //     ['en' => 'Dominica', 'ar' => 'دومينيكا'],
        //     ['en' => 'Dominican Republic', 'ar' => 'جمهورية الدومينيكان'],
        //     ['en' => 'Ecuador', 'ar' => 'الإكوادور'],
        //     ['en' => 'Egypt', 'ar' => 'مصر'],
        //     ['en' => 'El Salvador', 'ar' => 'السلفادور'],
        //     ['en' => 'Equatorial Guinea', 'ar' => 'غينيا الاستوائية'],
        //     ['en' => 'Eritrea', 'ar' => 'إريتريا'],
        //     ['en' => 'Estonia', 'ar' => 'إستونيا'],
        //     ['en' => 'Ethiopia', 'ar' => 'إثيوبيا'],
        //     ['en' => 'Falkland Islands (Malvinas)', 'ar' => 'جزر فوكلاند (مالفيناس)'],
        //     ['en' => 'Faroe Islands', 'ar' => 'جزر فارو'],
        //     ['en' => 'Fiji', 'ar' => 'فيجي'],
        //     ['en' => 'Finland', 'ar' => 'فنلندا'],
        //     ['en' => 'France', 'ar' => 'فرنسا'],
        //     ['en' => 'French Guiana', 'ar' => 'غيانا الفرنسية'],
        //     ['en' => 'French Polynesia', 'ar' => 'بولينيزيا الفرنسية'],
        //     ['en' => 'French Southern Territories', 'ar' => 'المقاطعات الجنوبية الفرنسية'],
        //     ['en' => 'Gabon', 'ar' => 'الغابون'],
        //     ['en' => 'Gambia', 'ar' => 'غامبيا'],
        //     ['en' => 'Georgia', 'ar' => 'جورجيا'],
        //     ['en' => 'Germany', 'ar' => 'ألمانيا'],
        //     ['en' => 'Ghana', 'ar' => 'غانا'],
        //     ['en' => 'Gibraltar', 'ar' => 'جبل طارق'],
        //     ['en' => 'Holy See (Vatican City State)', 'ar' => 'الفاتيكان'],
        //     ['en' => 'Honduras', 'ar' => 'هندوراس'],
        //     ['en' => 'Hong Kong', 'ar' => 'هونغ كونغ'],
        //     ['en' => 'Hungary', 'ar' => 'هنغاريا'],
        //     ['en' => 'Iceland', 'ar' => 'آيسلندا'],
        //     ['en' => 'India', 'ar' => 'الهند'],
        //     ['en' => 'Indonesia', 'ar' => 'إندونيسيا'],
        //     ['en' => 'Iran, Islamic Republic of', 'ar' => 'إيران'],
        //     ['en' => 'Iraq', 'ar' => 'العراق'],
        //     ['en' => 'Ireland', 'ar' => 'أيرلندا'],
        //     ['en' => 'Isle of Man', 'ar' => 'جزيرة مان'],
        //     ['en' => 'Israel', 'ar' => 'إسرائيل'],
        //     ['en' => 'Italy', 'ar' => 'إيطاليا'],
        //     ['en' => 'Jamaica', 'ar' => 'جامايكا'],
        //     ['en' => 'Japan', 'ar' => 'اليابان'],
        //     ['en' => 'Jersey', 'ar' => 'جيرسي'],
        //     ['en' => 'Jordan', 'ar' => 'الأردن'],
        //     ['en' => 'Kazakhstan', 'ar' => 'كازاخستان'],
        //     ['en' => 'Kenya', 'ar' => 'كينيا'],
        //     ['en' => 'Kiribati', 'ar' => 'كيريباس'],
        //     ['en' => 'Korea, Democratic People\'s Republic of', 'ar' => 'كوريا الشمالية'],
        //     ['en' => 'Korea, Republic of', 'ar' => 'كوريا الجنوبية'],
        //     ['en' => 'Kuwait', 'ar' => 'الكويت'],
        //     ['en' => 'Kyrgyzstan', 'ar' => 'قيرغيزستان'],
        //     ['en' => 'Lao People\'s Democratic Republic', 'ar' => 'لاوس'],
        //     ['en' => 'Latvia', 'ar' => 'لاتفيا'],
        //     ['en' => 'Lebanon', 'ar' => 'لبنان'],
        //     ['en' => 'Lesotho', 'ar' => 'ليسوتو'],
        //     ['en' => 'Liberia', 'ar' => 'ليبيريا'],
        //     ['en' => 'Libya', 'ar' => 'ليبيا'],
        //     ['en' => 'Liechtenstein', 'ar' => 'ليختنشتاين'],
        //     ['en' => 'Lithuania', 'ar' => 'ليتوانيا'],
        //     ['en' => 'Luxembourg', 'ar' => 'لوكسمبورغ'],
        //     ['en' => 'Macao', 'ar' => 'ماكاو'],
        //     ['en' => 'Macedonia, the Former Yugoslav Republic of', 'ar' => 'مقدونيا'],
        //     ['en' => 'Madagascar', 'ar' => 'مدغشقر'],
        //     ['en' => 'Malawi', 'ar' => 'مالاوي'],
        //     ['en' => 'Malaysia', 'ar' => 'ماليزيا'],
        //     ['en' => 'Maldives', 'ar' => 'المالديف'],
        //     ['en' => 'Mali', 'ar' => 'مالي'],
        //     ['en' => 'Malta', 'ar' => 'مالطا'],
        //     ['en' => 'Marshall Islands', 'ar' => 'جزر مارشال'],
        //     ['en' => 'Martinique', 'ar' => 'مارتينيك'],
        //     ['en' => 'Mauritania', 'ar' => 'موريتانيا'],
        //     ['en' => 'Mauritius', 'ar' => 'موريشيوس'],
        //     ['en' => 'Mayotte', 'ar' => 'مايوت'],
        //     ['en' => 'Mexico', 'ar' => 'المكسيك'],
        //     ['en' => 'Micronesia, Federated States of', 'ar' => 'ولايات ميكرونيزيا المتحدة'],
        //     ['en' => 'Moldova, Republic of', 'ar' => 'مولدوفا'],
        //     ['en' => 'Monaco', 'ar' => 'موناكو'],
        //     ['en' => 'Mongolia', 'ar' => 'منغوليا'],
        //     ['en' => 'Montenegro', 'ar' => 'الجبل الأسود'],
        //     ['en' => 'Montserrat', 'ar' => 'مونتسيرات'],
        //     ['en' => 'Morocco', 'ar' => 'المغرب'],
        //     ['en' => 'Mozambique', 'ar' => 'موزمبيق'],
        //     ['en' => 'Myanmar', 'ar' => 'ميانمار'],
        //     ['en' => 'Namibia', 'ar' => 'ناميبيا'],
        //     ['en' => 'Nauru', 'ar' => 'ناورو'],
        //     ['en' => 'Nepal', 'ar' => 'نيبال'],
        //     ['en' => 'Netherlands', 'ar' => 'هولندا'],
        //     ['en' => 'New Caledonia', 'ar' => 'كاليدونيا الجديدة'],
        //     ['en' => 'New Zealand', 'ar' => 'نيوزيلندا'],
        //     ['en' => 'Nicaragua', 'ar' => 'نيكاراغوا'],
        //     ['en' => 'Niger', 'ar' => 'النيجر'],
        //     ['en' => 'Nigeria', 'ar' => 'نيجيريا'],
        //     ['en' => 'Niue', 'ar' => 'نيوي'],
        //     ['en' => 'Norfolk Island', 'ar' => 'جزيرة نورفولك'],
        //     ['en' => 'Northern Mariana Islands', 'ar' => 'جزر ماريانا الشمالية'],
        //     ['en' => 'Norway', 'ar' => 'النرويج'],
        //     ['en' => 'Oman', 'ar' => 'عمان'],
        //     ['en' => 'Pakistan', 'ar' => 'باكستان'],
        //     ['en' => 'Palau', 'ar' => 'بالاو'],
        //     ['en' => 'Palestine, State of', 'ar' => 'فلسطين'],
        //     ['en' => 'Panama', 'ar' => 'بنما'],
        //     ['en' => 'Papua New Guinea', 'ar' => 'بابوا غينيا الجديدة'],
        //     ['en' => 'Paraguay', 'ar' => 'باراغواي'],
        //     ['en' => 'Peru', 'ar' => 'بيرو'],
        //     ['en' => 'Philippines', 'ar' => 'الفلبين'],
        //     ['en' => 'Pitcairn', 'ar' => 'بيتكيرن'],
        //     ['en' => 'Poland', 'ar' => 'بولندا'],
        //     ['en' => 'Portugal', 'ar' => 'البرتغال'],
        //     ['en' => 'Puerto Rico', 'ar' => 'بورتوريكو'],
        //     ['en' => 'Qatar', 'ar' => 'قطر'],
        //     ['en' => 'Réunion', 'ar' => 'ريونيون'],
        //     ['en' => 'Romania', 'ar' => 'رومانيا'],
        //     ['en' => 'Russian Federation', 'ar' => 'روسيا'],
        //     ['en' => 'Rwanda', 'ar' => 'رواندا'],
        //     ['en' => 'Saint Barthélemy', 'ar' => 'سان بارتيلمي'],
        //     ['en' => 'Saint Helena, Ascension and Tristan da Cunha', 'ar' => 'سانت هيلانة وأسينشين وتريستان دا كونها'],
        //     ['en' => 'Saint Kitts and Nevis', 'ar' => 'سانت كيتس ونيفيس'],
        //     ['en' => 'Saint Lucia', 'ar' => 'سانت لوسيا'],
        //     ['en' => 'Saint Martin (French part)', 'ar' => 'سانت مارتن (الجزء الفرنسي)'],
        //     ['en' => 'Saint Pierre and Miquelon', 'ar' => 'سان بيير وميكلون'],
        //     ['en' => 'Saint Vincent and the Grenadines', 'ar' => 'سانت فنسنت والغرينادين'],
        //     ['en' => 'Samoa', 'ar' => 'ساموا'],
        //     ['en' => 'San Marino', 'ar' => 'سان مارينو'],
        //     ['en' => 'Sao Tome and Principe', 'ar' => 'ساو تومي وبرينسيب'],
        //     ['en' => 'Saudi Arabia', 'ar' => 'المملكة العربية السعودية'],
        //     ['en' => 'Senegal', 'ar' => 'السنغال'],
        //     ['en' => 'Serbia', 'ar' => 'صربيا'],
        //     ['en' => 'Seychelles', 'ar' => 'سيشل'],
        //     ['en' => 'Sierra Leone', 'ar' => 'سيراليون'],
        //     ['en' => 'Singapore', 'ar' => 'سنغافورة'],
        //     ['en' => 'Sint Maarten (Dutch part)', 'ar' => 'سينت مارتن (الجزء الهولندي)'],
        //     ['en' => 'Slovakia', 'ar' => 'سلوفاكيا'],
        //     ['en' => 'Slovenia', 'ar' => 'سلوفينيا'],
        //     ['en' => 'Solomon Islands', 'ar' => 'جزر سليمان'],
        //     ['en' => 'Somalia', 'ar' => 'الصومال'],
        //     ['en' => 'South Africa', 'ar' => 'جنوب أفريقيا'],
        //     ['en' => 'South Georgia and the South Sandwich Islands', 'ar' => 'جورجيا الجنوبية وجزر ساندويتش الجنوبية'],
        //     ['en' => 'South Sudan', 'ar' => 'جنوب السودان'],
        //     ['en' => 'Spain', 'ar' => 'إسبانيا'],
        //     ['en' => 'Sri Lanka', 'ar' => 'سريلانكا'],
        //     ['en' => 'Sudan', 'ar' => 'السودان'],
        //     ['en' => 'Suriname', 'ar' => 'سورينام'],
        //     ['en' => 'Svalbard and Jan Mayen', 'ar' => 'سفالبارد ويان ماين'],
        //     ['en' => 'Swaziland', 'ar' => 'سوازيلاند'],
        //     ['en' => 'Sweden', 'ar' => 'السويد'],
        //     ['en' => 'Switzerland', 'ar' => 'سويسرا'],
        //     ['en' => 'Syrian Arab Republic', 'ar' => 'الجمهورية العربية السورية'],
        //     ['en' => 'Taiwan', 'ar' => 'تايوان'],
        //     ['en' => 'Tajikistan', 'ar' => 'طاجيكستان'],
        //     ['en' => 'Tanzania, United Republic of', 'ar' => 'تنزانيا'],
        //     ['en' => 'Thailand', 'ar' => 'تايلاند'],
        //     ['en' => 'Timor-Leste', 'ar' => 'تيمور الشرقية'],
        //     ['en' => 'Togo', 'ar' => 'توجو'],
        //     ['en' => 'Tokelau', 'ar' => 'توكيلاو'],
        //     ['en' => 'Tonga', 'ar' => 'تونغا'],
        //     ['en' => 'Trinidad and Tobago', 'ar' => 'ترينيداد وتوباغو'],
        //     ['en' => 'Tunisia', 'ar' => 'تونس'],
        //     ['en' => 'Turkey', 'ar' => 'تركيا'],
        //     ['en' => 'Turkmenistan', 'ar' => 'تركمانستان'],
        //     ['en' => 'Turks and Caicos Islands', 'ar' => 'جزر تركس وكايكوس'],
        //     ['en' => 'Tuvalu', 'ar' => 'توفالو'],
        //     ['en' => 'Uganda', 'ar' => 'أوغندا'],
        //     ['en' => 'Ukraine', 'ar' => 'أوكرانيا'],
        //     ['en' => 'United Arab Emirates', 'ar' => 'الإمارات العربية المتحدة'],
        //     ['en' => 'United Kingdom', 'ar' => 'المملكة المتحدة'],
        //     ['en' => 'United States', 'ar' => 'الولايات المتحدة الأمريكية'],
        //     ['en' => 'United States Minor Outlying Islands', 'ar' => 'الجزر الصغيرة النائية للولايات المتحدة'],
        //     ['en' => 'Uruguay', 'ar' => 'أوروغواي'],
        //     ['en' => 'Uzbekistan', 'ar' => 'أوزبكستان'],
        //     ['en' => 'Vanuatu', 'ar' => 'فانواتو'],
        //     ['en' => 'Venezuela, Bolivarian Republic of', 'ar' => 'فنزويلا'],
        //     ['en' => 'Viet Nam', 'ar' => 'فيتنام'],
        //     ['en' => 'Virgin Islands, British', 'ar' => 'جزر العذراء البريطانية'],
        //     ['en' => 'Virgin Islands, U.S.', 'ar' => 'جزر العذراء الأمريكية'],
        //     ['en' => 'Wallis and Futuna', 'ar' => 'واليس وفوتونا'],
        //     ['en' => 'Western Sahara', 'ar' => 'الصحراء الغربية'],
        //     ['en' => 'Yemen', 'ar' => 'اليمن'],
        //     ['en' => 'Zambia', 'ar' => 'زامبيا'],
        //     ['en' => 'Zimbabwe', 'ar' => 'زيمبابوي'],
        // ];

        foreach ($countries as $country) {
            Country::create([
                'name' => $country,
            ]);
        }
    }
}
